name: CI/CD

on: [push,pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rake
    - name: Log
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "contains(github.head_ref, 'release/v'): ${{ contains(github.head_ref, 'release/v') }}"
        echo "github.base_ref == 'master': ${{ github.base_ref == 'master' }}"
        echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ contains(github.head_ref, 'release/v') && github.base_ref == 'master' && github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release

